landmarks:
  [
    [6.0, 4.5],
    [6.0, -4.5],
    [0.0, -4.5],
    [0.0,4.5],
    [0.0,-1.5],
    [0.0,1.5],
    [3.0,-4.5],
    [3.0,4.5],
    [3.75,-2.25],
    [3.75,2.25]
  ]
walls:
  left: 0.0
  right: 7.0
  up: 5.0
  down: -5.0