landmarks:
  [
    [6.0, 4.5, 1.0],
    [6.0, -4.5, 1.0],
    [0.0, -4.5, 1.0],
    [0.0, 4.5, 1.0],
    [0.0, -1.5, 1.0],
    [0.0, 1.5, 1.0],
    [3.0, -4.5, 1.0],
    [3.0, 4.5, 1.0],
    [3.75, -2.25, 1.0],
    [3.75, 2.25, 1.0]
  ]
walls:
  left: 0.0
  right: 7.0
  up: 5.0
  down: -5.0
  floor: 0.0
  ceiling: 4.0
